"""update notification table

Revision ID: c57a7b1c360f
Revises: ee9e90042287
Create Date: 2024-07-31 00:29:12.905611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c57a7b1c360f'
down_revision = 'ee9e90042287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('sender_id')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('MESSAGE', 'NOTIFICATION', 'ACTIVITY', name='messagetype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
