"""initial migration

Revision ID: ee9e90042287
Revises: 
Create Date: 2024-07-31 00:19:45.112415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee9e90042287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    notificationtype_enum = sa.Enum('MESSAGE', 'NOTIFICATION', 'ACTIVITY', name='notificationtype')
    notificationtype_enum.create(op.get_bind())
    
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.Enum('MESSAGE', 'NOTIFICATION', 'ACTIVITY', name='notificationtype'), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('notification_sender_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trendit3_user', ['recipient_id'], ['id'])
        # batch_op.drop_column('sender_id')
        # batch_op.drop_column('createdAt')
        # batch_op.drop_column('type')
        # batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('MESSAGE', 'NOTIFICATION', 'ACTIVITY', name='messagetype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_sender_id_fkey', 'trendit3_user', ['sender_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('read')
        batch_op.drop_column('title')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
