"""empty message

Revision ID: 284b1c154585
Revises: da9e9e34c55e
Create Date: 2024-03-11 09:05:12.456058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284b1c154585'
down_revision = 'da9e9e34c55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_i_ds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('facebook_id', sa.String(length=200), nullable=True),
    sa.Column('instagram_id', sa.String(length=200), nullable=True),
    sa.Column('tiktok_id', sa.String(length=200), nullable=True),
    sa.Column('x_id', sa.String(length=200), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_message_status', schema=None) as batch_op:
        batch_op.drop_constraint('user_message_status_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_message_status_message_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trendit3_user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'notification', ['message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_message_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_message_status_message_id_fkey', 'notification', ['message_id'], ['id'])
        batch_op.create_foreign_key('user_message_status_user_id_fkey', 'trendit3_user', ['user_id'], ['id'])

    op.drop_table('social_i_ds')
    # ### end Alembic commands ###
