"""empty message

Revision ID: 39f3af3d5a7a
Revises: fc144a1a6db6
Create Date: 2024-05-12 21:56:28.662261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f3af3d5a7a'
down_revision = 'fc144a1a6db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_symbol', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.drop_column('currency_symbol')

    # ### end Alembic commands ###
