"""empty message

Revision ID: 5e7bda742467
Revises: 42d3de37c2b2
Create Date: 2024-05-23 17:22:26.531366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7bda742467'
down_revision = '42d3de37c2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pricingcategory_enum = sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='pricingcategory')
    pricingcategory_enum.create(op.get_bind())
    
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('ADVERT', 'ENGAGEMENT', name='pricingcategory'), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
