"""empty message

Revision ID: 7792ff3b0c55
Revises: 772852352e8b
Create Date: 2024-03-17 21:10:13.352348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7792ff3b0c55'
down_revision = '772852352e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CREDIT', 'DEBIT', 'PAYMENT', 'WITHDRAW', name='transactiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.Enum('CREDIT', 'DEBIT', 'PAYMENT', 'WITHDRAW', name='transactiontype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
