"""empty message

Revision ID: 963d5b8e04da
Revises: d1abfe5a66c8
Create Date: 2024-05-03 17:25:41.734147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963d5b8e04da'
down_revision = 'd1abfe5a66c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('price_earn', sa.Float(), nullable=False),
    sa.Column('price_pay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('task_medias',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_media_id_fkey', type_='foreignkey')
        batch_op.drop_column('media_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_media_id_fkey', 'media', ['media_id'], ['id'])

    op.drop_table('task_medias')
    op.drop_table('pricing')
    # ### end Alembic commands ###
