"""empty message

Revision ID: aad75da1a5c8
Revises: 284b1c154585
Create Date: 2024-03-11 11:52:40.976222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad75da1a5c8'
down_revision = '284b1c154585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_account', schema=None) as batch_op:
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
