"""empty message

Revision ID: bd19cbe3d529
Revises: 5e7bda742467
Create Date: 2024-05-25 17:35:12.922865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd19cbe3d529'
down_revision = '5e7bda742467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        

    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('_balance')

    with op.batch_alter_table('pricing', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=postgresql.ENUM('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='pricingcategory'),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
