"""Create needed settings tables

Revision ID: c544c9d1636a
Revises: 002a12b122f7
Create Date: 2024-03-07 01:02:37.730167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c544c9d1636a'
down_revision = '002a12b122f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_new_features', sa.Boolean(), nullable=True),
    sa.Column('email_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('email_money_earned', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_features', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('in_app_money_earned', sa.Boolean(), nullable=True),
    sa.Column('push_new_features', sa.Boolean(), nullable=True),
    sa.Column('push_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('push_money_earned', sa.Boolean(), nullable=True),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two_factor_method', sa.String(length=150), nullable=True),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(length=150), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.drop_table('user_preference')
    op.drop_table('security_setting')
    op.drop_table('notification_preference')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
