"""empty message

Revision ID: da9e9e34c55e
Revises: 30cf9383436c
Create Date: 2024-03-10 22:33:18.592742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9e9e34c55e'
down_revision = '30cf9383436c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trendit3_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_secret', sa.String(length=255), nullable=True))
        batch_op.drop_column('two_factor_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trendit3_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('two_fa_secret')

    # ### end Alembic commands ###
