"""initial migration

Revision ID: dd37bf138786
Revises: 
Create Date: 2024-05-30 13:29:25.300310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd37bf138786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('category', sa.Enum('ADVERT', 'ENGAGEMENT', name='pricingcategory'), nullable=False),
    sa.Column('price_earn', sa.Float(), nullable=False),
    sa.Column('price_pay', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'Admin', 'JUNIOR_ADMIN', 'ADVERTISER', 'EARNER', 'CUSTOMER', name='rolenames'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('temp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trendit3_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('thePassword', sa.String(length=255), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('two_fa_secret', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('local_government', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=50), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=80), nullable=False),
    sa.Column('bank_code', sa.Integer(), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=250), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_fee_paid', sa.Boolean(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trendit3_user_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MESSAGE', 'NOTIFICATION', 'ACTIVITY', name='messagetype'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('referral_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=900), nullable=True),
    sa.Column('status', sa.String(length=900), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('username')
    )
    op.create_table('social_i_ds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('facebook_id', sa.String(length=200), nullable=True),
    sa.Column('instagram_id', sa.String(length=200), nullable=True),
    sa.Column('tiktok_id', sa.String(length=200), nullable=True),
    sa.Column('x_id', sa.String(length=200), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('google_verified', sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='sociallinksstatus'), nullable=True),
    sa.Column('facebook_id', sa.String(length=200), nullable=True),
    sa.Column('facebook_verified', sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='sociallinksstatus'), nullable=True),
    sa.Column('instagram_id', sa.String(length=200), nullable=True),
    sa.Column('instagram_verified', sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='sociallinksstatus'), nullable=True),
    sa.Column('tiktok_id', sa.String(length=200), nullable=True),
    sa.Column('tiktok_verified', sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='sociallinksstatus'), nullable=True),
    sa.Column('x_id', sa.String(length=200), nullable=True),
    sa.Column('x_verified', sa.Enum('IDLE', 'PENDING', 'VERIFIED', 'REJECTED', name='sociallinksstatus'), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socialverification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='socialverificationstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('task_key', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_allocated', sa.Integer(), nullable=True),
    sa.Column('total_success', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Enum('COMPLETE', 'PENDING', 'FAILED', 'ABANDONED', name='taskpaymentstatus'), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'DECLINED', name='taskstatus'), nullable=False),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_key')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.Enum('CREDIT', 'DEBIT', 'PAYMENT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], )
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_name', sa.String(), nullable=True),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('currency_symbol', sa.String(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_no', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advert_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('target_country', sa.String(length=120), nullable=False),
    sa.Column('target_state', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=80), nullable=False),
    sa.Column('account_link', sa.String(length=120), nullable=False),
    sa.Column('engagements_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('media_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_new_features', sa.Boolean(), nullable=True),
    sa.Column('email_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('email_money_earned', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_features', sa.Boolean(), nullable=True),
    sa.Column('in_app_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('in_app_money_earned', sa.Boolean(), nullable=True),
    sa.Column('push_new_features', sa.Boolean(), nullable=True),
    sa.Column('push_new_tasks', sa.Boolean(), nullable=True),
    sa.Column('push_money_earned', sa.Boolean(), nullable=True),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recipient_code', sa.String(length=255), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.String(), nullable=False),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_code'),
    sa.UniqueConstraint('recipient_type')
    )
    op.create_table('security_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two_factor_method', sa.String(length=150), nullable=True),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_message_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READ', 'UNREAD', name='messagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['notification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('READ', 'UNREAD', name='messagestatus'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], )
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(length=150), nullable=False),
    sa.Column('user_settings_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_id'], ['user_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=300), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('material', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('item_img_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_img_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=200), nullable=True),
    sa.Column('lastname', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_picture_id', sa.Integer(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_picture_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_medias',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], )
    )
    op.create_table('task_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('reward_money', sa.Float(), nullable=True),
    sa.Column('account_name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('proof_screenshot_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proof_screenshot_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share')
    op.drop_table('like_log')
    op.drop_table('comment')
    op.drop_table('task_performance')
    op.drop_table('task_medias')
    op.drop_table('profile')
    op.drop_table('item')
    op.drop_table('user_preference')
    op.drop_table('user_notification')
    op.drop_table('user_message_status')
    op.drop_table('security_setting')
    op.drop_table('recipient')
    op.drop_table('notification_preference')
    op.drop_table('media')
    op.drop_table('engagement_task')
    op.drop_table('advert_task')
    op.drop_table('withdrawal')
    op.drop_table('wallet')
    op.drop_table('user_settings')
    op.drop_table('user_roles')
    op.drop_table('transaction')
    op.drop_table('task')
    op.drop_table('socialverification')
    op.drop_table('social_links')
    op.drop_table('social_i_ds')
    op.drop_table('referral_history')
    op.drop_table('payment')
    op.drop_table('one_time_token')
    op.drop_table('notification')
    op.drop_table('membership')
    op.drop_table('bank_account')
    op.drop_table('address')
    op.drop_table('trendit3_user')
    op.drop_table('temp_user')
    op.drop_table('role')
    op.drop_table('pricing')
    # ### end Alembic commands ###
