"""empty message

Revision ID: fc144a1a6db6
Revises: 963d5b8e04da
Create Date: 2024-05-07 19:23:01.045675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc144a1a6db6'
down_revision = '963d5b8e04da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('google_verified', sa.Boolean(), nullable=True),
    sa.Column('facebook_id', sa.String(length=200), nullable=True),
    sa.Column('facebook_verified', sa.Boolean(), nullable=True),
    sa.Column('instagram_id', sa.String(length=200), nullable=True),
    sa.Column('instagram_verified', sa.Boolean(), nullable=True),
    sa.Column('tiktok_id', sa.String(length=200), nullable=True),
    sa.Column('tiktok_verified', sa.Boolean(), nullable=True),
    sa.Column('x_id', sa.String(length=200), nullable=True),
    sa.Column('x_verified', sa.Boolean(), nullable=True),
    sa.Column('trendit3_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trendit3_user_id'], ['trendit3_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socialverification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='socialverificationstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['trendit3_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialverification')
    op.drop_table('social_links')
    # ### end Alembic commands ###
